name = "mv-face-recognition-api"
main = "src/index.ts"
compatibility_date = "2024-11-08"

# Enable Workers Logs
[observability]
enabled = true

[[kv_namespaces]]
binding = "METADATA_KV"
id = "890d77e11bfc4623ac4ef56db6b9a4ab"
preview_id = "ba09879957074c0892d9a208f2fb1e5c"

[[kv_namespaces]]
binding = "MODAL_JOBS"
id = "9096b9cd7c204ad2b511c173057e85ab"
preview_id = "9096b9cd7c204ad2b511c173057e85ab"

[[r2_buckets]]
binding = "VIDEOS_BUCKET"
bucket_name = "mv-face-recognition-videos"
preview_bucket_name = "mv-face-recognition-videos-preview"

[vars]
ALLOWED_ORIGINS = "https://mv-face-recognition-api.herballemon.workers.dev,https://mv-face-recognition.pages.dev,https://a0a857b9.mv-face-recognition.pages.dev,https://d7308ddf.mv-face-recognition.pages.dev,https://371f3248.mv-face-recognition.pages.dev,http://localhost:5173"
ENVIRONMENT = "production"
LOG_LEVEL = "info"  # Options: debug, info, warn, error, none

