name: Sync to Hugging Face hub

on:
  push:
    branches:
      - main

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "4060163+yellowcandle@users.noreply.github.com"
          git config --global user.name "yellowcandle"
          git remote add hf https://user:${HF_TOKEN}@huggingface.co/spaces/yellowcandle/mv-face-recognition
          git push hf main --force
